# mkvcleaner
:doctype: article
:toclevels: 3
:hide-uri-scheme:
:icons: font
:idprefix:
:idseparator: -
:source-language: shell
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :information_source:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

== Overview

mkvcleaner removes certain metadata from Matroska (.mkv) video files.

. Segment info title
. Video track 1 name
. Audio track 1 name

Optionally, mkvcleaner can set the first embedded subtitle track in your preferred language to default, so that subtitle track will automatically show when the video is opened in a video player that supports embedded subtitles, such as VLC.

== Installation

. Install MKVToolnix.
.. This program depends on mkvpropedit.exe from the MKVToolnix package.
. Run Setup-mkvcleaner-x64.exe.
.. Setup needs administrator privileges in order to modify the registry to add Explorer context menu entries.

== Usage

=== Windows Explorer

Right-click on any folder, or select one or more .mkv files and right-click on one, and choose "mkvcleaner" from the context menu.

=== CLI

`mkvcleaner <folder_or_file_path1> [<folder_or_file_path2> ...]`

== Options

Some options can be set in the config.json file included with this distribution. This file can be found in `%LOCALAPPDATA\mkvcleaner` after install.

`mkvtoolnix_path`: Specify the full path to the folder containing `mkvpropedit.exe` on your system, in case `mkvpropedit` is not found in your `PATH`. Typically `C:\\Program Files\\MKVToolNix`.


== Notes

`pip install pyinstaller`

`pyinstaller .\mkvcleaner.spec --distpath .\dist\ --workpath .pyinstaller`

`pyi-set_version.exe .\file_version_info.txt .\dist\mkvcleaner.exe`
