title = 'mkvcleaner settings'

mkvtoolnix_path='C:\Program Files\MKVToolNix'
language = 'en'

debug_mode = false

# Whether or not to use color in the program output
use_color = true

# Whether or not to set the first subtitle track of that language as the default
set_default_subtitle_track = true

# Whether or not to pause and wait for user to press Enter before exiting
pause_before_exit = true
